// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQcsw04BkXmuz5wnt8Q_5maVvQMYYK0Js',
    appId: '1:767615754171:web:0e0e563ee0e2f3a253ee9e',
    messagingSenderId: '767615754171',
    projectId: 'fir-flutter-project-e7898',
    authDomain: 'fir-flutter-project-e7898.firebaseapp.com',
    storageBucket: 'fir-flutter-project-e7898.appspot.com',
    measurementId: 'G-7NJTVH4EKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgaNR1YTcvNWOV9iRQ0jkifDadMJvrkVM',
    appId: '1:767615754171:android:897c823a2f6e8b6253ee9e',
    messagingSenderId: '767615754171',
    projectId: 'fir-flutter-project-e7898',
    storageBucket: 'fir-flutter-project-e7898.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuu60KyMxET6ekWiTOqUEA13GAVD4XoEs',
    appId: '1:767615754171:ios:b037643447f462ad53ee9e',
    messagingSenderId: '767615754171',
    projectId: 'fir-flutter-project-e7898',
    storageBucket: 'fir-flutter-project-e7898.appspot.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuu60KyMxET6ekWiTOqUEA13GAVD4XoEs',
    appId: '1:767615754171:ios:b5a9ce7b4e8311c853ee9e',
    messagingSenderId: '767615754171',
    projectId: 'fir-flutter-project-e7898',
    storageBucket: 'fir-flutter-project-e7898.appspot.com',
    iosBundleId: 'com.example.firebaseProject.RunnerTests',
  );
}
