// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA44TiYjzM_258DNhc7pzP-EjhOhto0iDw',
    appId: '1:115526236151:web:53a2267472d2c3827820f2',
    messagingSenderId: '115526236151',
    projectId: 'chat-app-demo-a9598',
    authDomain: 'chat-app-demo-a9598.firebaseapp.com',
    storageBucket: 'chat-app-demo-a9598.appspot.com',
    measurementId: 'G-24ND0QX28Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCift-HgJCkjZfX4JiTEgkvA_p2T5vOZ1M',
    appId: '1:115526236151:android:3747460eb11008197820f2',
    messagingSenderId: '115526236151',
    projectId: 'chat-app-demo-a9598',
    storageBucket: 'chat-app-demo-a9598.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv6LO02fH_c1R9y8FUkrqx5MpL1vwy4-I',
    appId: '1:115526236151:ios:ab0cfcedcb4fb54c7820f2',
    messagingSenderId: '115526236151',
    projectId: 'chat-app-demo-a9598',
    storageBucket: 'chat-app-demo-a9598.appspot.com',
    androidClientId: '115526236151-psdgqu35ssqr8tgtmihabtacechthiak.apps.googleusercontent.com',
    iosClientId: '115526236151-ro7ovs55c8uq3fdqt6fqtd2ffit0uhcp.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv6LO02fH_c1R9y8FUkrqx5MpL1vwy4-I',
    appId: '1:115526236151:ios:4509fdebd9e04cf37820f2',
    messagingSenderId: '115526236151',
    projectId: 'chat-app-demo-a9598',
    storageBucket: 'chat-app-demo-a9598.appspot.com',
    androidClientId: '115526236151-psdgqu35ssqr8tgtmihabtacechthiak.apps.googleusercontent.com',
    iosClientId: '115526236151-v73pp2tv067qhd2jf2s5qsc6chgjbrik.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProject.RunnerTests',
  );
}
